services:
  fetcher-tester:
    build:
      context: .
      args:
        DOMAIN: ${test_hostname}
    env_file:
        .env
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
